services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
  frontend:
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

      